#!/usr/bin/env sh

set -eu

readonly PROG='shebang-run'
readonly VERSION='0.1.0'

version() {
  printf '%s\n' "$PROG v$VERSION"
}

usage() {
  cat <<EOF
Run a file according to the shebang line.

Usage:
  ${PROG} [--] <file> [<args>...]
  ${PROG} --help
  ${PROG} --version

Options:
  --help      Show this help.
  --version   Show version.
EOF
}

run() {
  filepath="${1:?}"

  shift
  first_line="$(head -n 1 -- "$filepath")"
  without_shebang_symbol="${first_line#"#!"}"
  if [ "$without_shebang_symbol" = "$first_line" ]; then
    printf '%s\n' "$PROG: not found shebang in $filepath" >&2
    return 1
  fi
  $without_shebang_symbol -- "$filepath" "$@"
}

main() {
  while [ $# -gt 0 ]; do
    case "$1" in
      '--')
        shift
        break
        ;;
      '--help')
        usage
        return 0
        ;;
      '--version')
        version
        return 0
        ;;
      '-'*)
        printf '%s\n' "$PROG: unknown option: $1" >&2
        return 1
        ;;
      *) break ;;
    esac
  done
  if [ $# -eq 0 ]; then
    usage
    return 1
  fi
  run "$@"
}

main "$@"
